language: python
python: "3.8"
cache: pip
install:
  # pyflakes hasn't bumped the version in setup.py
  - pip install git+https://github.com/pycqa/pyflakes
  - pip install -r requirements.txt
script:
  - flake8 .
  - pytest