on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
      - name: Install pytest
        run: pip install pytest
      - name: Test
        run: pytest
